<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datos = [
            array(
                'nombre' =>  "bife",
                'precio' => 15,
                'imagen' => "bife.webp",
                'descripcion' => "Guarnición: papas fritas/cocidas o patacones, ensalada, salsas.275 gramos",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "picaña",
                'precio' => 15,
                'imagen' => "picaña.jpg",
                'descripcion' => "Guarnición: papas fritas/cocidas o patacones, ensalada, salsas.275 gramos",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "lomo",
                'precio' => 15,
                'imagen' => "lomo.jpg",
                'descripcion' => "Guarnición: papas fritas/cocidas o patacones, ensalada, salsas.275 gramos",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "ribeye",
                'precio' => 15,
                'imagen' => "ribeye.jpg",
                'descripcion' => "Guarnición: papas fritas/cocidas o patacones, ensalada, salsas.275 gramos",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "costilla-de-cerdo",
                'precio' => 15,
                'imagen' => "costilla-de-cerdo.jpg",
                'descripcion' => "Guarnición: papas fritas/cocidas o patacones, ensalada, salsas.275 gramos.(baby back ribs)",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "tomhawak",
                'precio' => 15,
                'imagen' => "tomhawak.jpg",
                'descripcion' => "Guarnición: papas fritas/cocidas o patacones, ensalada, salsas.275 gramos",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "moro-pollo",
                'precio' => 6.5,
                'imagen' => "moro-pollo.jpg",
                'descripcion' => "moro de fréjol, salsa de queso, suprema de pollo asado.              ",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "moro-carne",
                'precio' => 6.5,
                'imagen' => "moro-carne.jpg",
                'descripcion' => "moro de fréjol, salsa de queso, filete de carne asada.              ",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "moro-chuleta",
                'precio' => 6.5,
                'imagen' => "moro-chuleta.jpg",
                'descripcion' => "moro de fréjol, salsa de queso, chuleta asada.              ",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "moro-doble",
                'precio' => 8,
                'imagen' => "moro-doble.jpg",
                'descripcion' => "moro de fréjol, salsa de queso, dos carnes de su eleccion.              ",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "parrillada",
                'precio' => 37,
                'imagen' => "parrillada.jpg",
                'descripcion' => "Carne, pollo, chorizo parrillero, chorizo artesanal, chuleta, camarón, chinchulines | Guarnición: papas fritas/ cocidas o patacones, ensalada, salsas (PARA 4 A 5 PERSONAS).",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "parrillada-personal",
                'precio' => 15,
                'imagen' => "parrillada-personal.jpg",
                'descripcion' => "Carne, pollo, chorizo parrillero, chorizo artesanal, chuleta, camarón | Guarnición: papas fritas/ cocidas o patacones, ensalada, salsas (1 PERSONA).",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "carne-asada",
                'precio' => 6,
                'imagen' => "carne-asada.jpg",
                'descripcion' => "Filete de lomo de xx gr. | Guarnición: papas fritas/cocidas o patacones, ensalada, salsa.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "pollo-asada",
                'precio' => 6,
                'imagen' => "pollo-asada.jpg",
                'descripcion' => "Suprema de pollo de xx gr. | Guarnición: papas fritas/cocidas o patacones, ensalada, salsa.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "chuleta-asada",
                'precio' => 6,
                'imagen' => "chuleta-asada.jpg",
                'descripcion' => "Chuleta de cerdo de xx gr. | Guarnición: papas fritas/cocidas o patacones, ensalada, salsa.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "picadas-monkey",
                'precio' => 6.5,
                'imagen' => "picadas-monkey.jpg",
                'descripcion' => "Carne, pollo, chorizo parrillero, chorizo artesanal,cuerito, camarón  (xx gr. De proteina) | Guarnición: papas fritas/cocidas o patacones, ensalada, salsa.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "hamburguesa-monkey",
                'precio' => 7.5,
                'imagen' => "hamburguesa-monkey.jpg",
                'descripcion' => "Doble porciòn de 130 gr. de carne,queso, cheddar,jamón, tocino, vegetales. | Guarnición: papas fritas, salsas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "alitas-bbq",
                'precio' => 7.5,
                'imagen' => "alitas-bbq.jpg",
                'descripcion' => "6 unidades de alitas | Guarnición: papas fritas/cocidas o patacones, salsas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "combo-mixto",
                'precio' => 22,
                'imagen' => "combo-mixto.jpg",
                'descripcion' => "12 unidades de alitas, 4 unidades de muslo, 10 unidades decamarones. | Guarnición: papas fritas/cocidas o patacones, salsas. | Salsas : salsas BBQ, mostaza miel, bufalo.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "combo-burguer",
                'precio' => 20,
                'imagen' => "combo-burguer.jpg",
                'descripcion' => "6 unidades de alitas, 3 hamburguesas. | Salsas : salsas BBQ, mostaza miel, bufalo. | Guarnición: papas fritas o patacones, salsas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "mix-de-chorizos",
                'precio' => 8,
                'imagen' => "mix-de-chorizos.jpg",
                'descripcion' => "Chorizo parrillero, chorizo artesanal,papas fritas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "porcion-de-alitas",
                'precio' => 5,
                'imagen' => "porcion-de-alitas.jpg",
                'descripcion' => "6 unidades de alitas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "porcion-de-ensalada",
                'precio' => 1.5,
                'imagen' => "porcion-de-ensalada.jpg",
                'descripcion' => "lechuga, tomate, cebolla, aderezo.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "porcion-de-moro",
                'precio' => 2.5,
                'imagen' => "porcion-de-moro.jpg",
                'descripcion' => "Moro de frèjol, salsa de queso.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "porcion-de-papas",
                'precio' => 2,
                'imagen' => "porcion-de-papas.jpg",
                'descripcion' => "Papa chola frita.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "porcion-de-patacones",
                'precio' => 2.5,
                'imagen' => "porcion-de-patacones.jpg",
                'descripcion' => "Porciòn de patacos.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "mora",
                'precio' => 2,
                'imagen' => "mora.jpg",
                'descripcion' => "Copa de jugo.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "fresa",
                'precio' => 2,
                'imagen' => "fresa.jpg",
                'descripcion' => "Copa de jugo.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "piña",
                'precio' => 2,
                'imagen' => "piña.jpg",
                'descripcion' => "Copa de jugo.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "jamaica",
                'precio' => 2,
                'imagen' => "jamaica.jpg",
                'descripcion' => "Copa de jugo.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "limon",
                'precio' => 2,
                'imagen' => "limon.jpg",
                'descripcion' => "Copa de jugo.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "jarra-de-mora",
                'precio' => 4,
                'imagen' => "jarra-de-mora.jpg",
                'descripcion' => "Jarra de jugo(5 vasos).",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "jarra-de-fresa",
                'precio' => 4,
                'imagen' => "jarra-de-fresa.jpg",
                'descripcion' => "Jarra de jugo(5 vasos).",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "jarra-de-piña",
                'precio' => 4,
                'imagen' => "jarra-de-piña.jpg",
                'descripcion' => "Jarra de jugo(5 vasos).",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "jarra-de-jamaica",
                'precio' => 4,
                'imagen' => "jarra-de-jamaica.jpg",
                'descripcion' => "Jarra de jugo(5 vasos).",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "jarra-de-limon",
                'precio' => 4,
                'imagen' => "jarra-de-limon.jpg",
                'descripcion' => "Jarra de jugo(5 vasos).",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "gaseosa-personal",
                'precio' => 0.75,
                'imagen' => "gaseosa-personal.jpg",
                'descripcion' => "Bebida con gas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "gaseosa-1-litro",
                'precio' => 2,
                'imagen' => "gaseosa-1-litro.jpg",
                'descripcion' => "Bebida con gas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "gaseosa-3-litros",
                'precio' => 4,
                'imagen' => "gaseosa-3-litros.jpg",
                'descripcion' => "Bebida con gas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "botella-de-agua-personal",
                'precio' => 0.75,
                'imagen' => "botella-de-agua-personal.jpg",
                'descripcion' => "Bebida con gas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "club-verde",
                'precio' => 2.5,
                'imagen' => "club-verde.jpg",
                'descripcion' => "750 ml.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "pilsener-light",
                'precio' => 2,
                'imagen' => "pilsener-light.jpg",
                'descripcion' => "750 ml.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "pilsener-negra",
                'precio' => 2,
                'imagen' => "pilsener-negra.jpg",
                'descripcion' => "750 ml.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "corona",
                'precio' => 3,
                'imagen' => "corona.jpg",
                'descripcion' => "355 ml.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "dalquiri-fresa-o-mora",
                'precio' => 4,
                'imagen' => "dalquiri-fresa-o-mora.jpg",
                'descripcion' => "Ron blanco, fresa o mora, hielo, azucar.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "cuba-libre",
                'precio' => 4,
                'imagen' => "cuba-libre.jpg",
                'descripcion' => "Jugo de limon, ron blanco 6 de soda.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "piña-colada",
                'precio' => 5,
                'imagen' => "piña-colada.jpg",
                'descripcion' => "piña, ron blanco, crema de coco sin azúcar, cubitos de hielo, azúcar blanco, granaduna.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "mojito",
                'precio' => 4,
                'imagen' => "mojito.jpg",
                'descripcion' => "Azúcar blanco, hierbabuena,  menta,  zumo de limon ron blanco,Soda con gas.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "caipiriña",
                'precio' => 4,
                'imagen' => "caipiriña.jpg",
                'descripcion' => "Limòn,azúcar,Hielo, ron blanco.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "michelada",
                'precio' => 4,
                'imagen' => "michelada.jpg",
                'descripcion' => "Cerveza, limon, sal, maracuya.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "sangria",
                'precio' => 4,
                'imagen' => "sangria.jpg",
                'descripcion' => "Vino tinto, Refresco de limón (soda),ron blanc, naranja, limón, manzana, fresa, Azúcar.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array(
                'nombre' =>  "copa-de-vino",
                'precio' => 3,
                'imagen' => "copa-de-vino.jpg",
                'descripcion' => "Vino tinto.",
                'disponible' => true,
                'promo_id' => null,
                'rating' => 0,
                'categoria_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
        ];

        DB::table('productos')->insert($datos);
    }
}
